### ISSUE TITLE
Add booters

### ISSUE THREAD

**Issue by anhcraft** [anhcraft/Battle-Issues#5]
Boosters are used to multiply the final exp/money.
```
booster_X:
    name: "aa"
    description:
    - Basic booster
    money_multiplier: 1.2
    exp_multiplier: 1.5
```
